### ISSUE TITLE
Tests may hang on some FreeBSD systems

### ISSUE THREAD

**Issue by eserte** [atoomic/XS-Logger#1]
On some of my FreeBSD systems the t/fork.t and t/levels.t tests may hang.
I can provide more information if needed.

**Comment by atoomic** [comment]
Feel free to add a link or extract output, right now it s in very early development stage and I'm expecting multiple errors like this that I would gladly fix.

thanks

**Comment by atoomic** [comment]
Thanks will going to simply use a directory lol

**Comment by atoomic** [comment]
fixed by b5c441c4787ea3a3f4b8d3e25bf21fee3561af18
